<a href="https://colab.research.google.com/github/ramiro-l/ModelosYSimulacionFAMAF/blob/main/Pr%C3%A1ctico8-Chequeos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chequeos para revisar el Practico 8

# Ej 1

\begin{bmatrix}
0,25 & 0.5 & 0.5 \\
0,5 & 0 & 0.5 \\
0,5 & 0 & 0.5 \\
\end{bmatrix}

In [ ]:
import numpy as np
A = np.array([[0.25, 0.5, 0.25],
              [0.5,  0, 0.5 ],
              [0.5,  0, 0.5 ]])
print(A @ A)
# np.linalg.matrix_power(A, 2)

[[0.4375 0.125  0.4375]
 [0.375  0.25   0.375 ]
 [0.375  0.25   0.375 ]]


In [ ]:
print(A @ A @ A)
# np.linalg.matrix_power(A, 3)

[[0.390625 0.21875  0.390625]
 [0.40625  0.1875   0.40625 ]
 [0.40625  0.1875   0.40625 ]]


In [ ]:
print(A @ A @ A @ A)
# np.linalg.matrix_power(A, 4)

[[0.40234375 0.1953125  0.40234375]
 [0.3984375  0.203125   0.3984375 ]
 [0.3984375  0.203125   0.3984375 ]]


# Ej 2.c

\begin{bmatrix}
1/2 & 1/4 & 1/4 \\
1/3 & 0 & 2/3 \\
1/2 & 1/2 & 0 \\
\end{bmatrix}

In [ ]:
import numpy as np
B = np.array([
                [1/2, 1/4, 1/4],
                [1/3, 0  , 2/3],
                [1/2, 1/2, 0  ]
             ])

print(B @ B)
# np.linalg.matrix_power(B, 2)

[[0.45833333 0.25       0.29166667]
 [0.5        0.41666667 0.08333333]
 [0.41666667 0.125      0.45833333]]


# Ej 3.b

\begin{bmatrix}
1/2 & 1/2 \\
2/3 & 1/3 \\
\end{bmatrix}

In [ ]:
(3/7) + (4/7) * (-1/6)**3

0.42592592592592593

In [ ]:
import numpy as np
C = np.array([
                [1/2, 1/2],
                [2/3, 1/3]
             ])

print(C @ C @ C)
# np.linalg.matrix_power(C, 3)

[[0.56944444 0.43055556]
 [0.57407407 0.42592593]]


## Ej 4

\begin{bmatrix}
0 & 1/2 & 1/2 \\
1/2 & 0 & 1/2 \\
1/2 & 1/2 & 0 \\
\end{bmatrix}

In [2]:
def p_ii(n):
    return 1/3 + 2/3 * (-1/2)**n

In [3]:
import numpy as np
P = np.array([
            [0, 1/2, 1/2],
            [1/2, 0, 1/2],
            [1/2, 1/2, 0]
             ])

def matrix_p_ii(n):
    matrix = np.linalg.matrix_power(P, n)
    return matrix[0][0]

In [4]:
# TEST

digits = 10
fail_test = 0
for n in range(1, 1_000):
    a = round(p_ii(n), digits)
    b = round(matrix_p_ii(n), digits)
    fail_test += a != b
print(f"Fail tests: {fail_test}")

Fail tests: 0
